### PR TITLE
Add missing objects.c items

### PR DESCRIPTION
**Pull request by Ernegien**

### CODE REVIEW

**Comment by Ernegien** [comment]
The object structure definitions can be checked via 
image
The first word after the tag group is the structure size
image
and 0x5C into the definition contains the inheritance hierarchy; in this case, object -> unit -> biped
image


Most object engine (not tag) data access is done via `object_get_and_verify_type` and `object_try_and_get_and_verify_type`, both taking a datum index/handle and object type as inputs doing a datum lookup against the `object_header_data` array returning a pointer to the requested `object_data_t` data.

Object types are loosely defined (possibly not comprehensive) as follows. They have bitmask tendencies, but I believe they're still treated as an enum, otherwise the -1 wouldn't make much sense in terms of flags.
```
-1 = none/obje
1 = bipd
2 = vehi
3 = unit
4 = weap
8 = eqip
0x10 = garb
0x1C = item
0x20 = proj
0x80 = mach
0x100 = ctrl
0x200 = lifi
0x380 = devi
```

**Comment by Ernegien** [comment]
This one should be ready for review. I've left the assembly comments in for easy look-ups which can be removed prior to merge. I'm happy to split this into smaller PRs but I'd imagine actual code is what will require more scrutiny than just type info.

**Comment by mborgerson** [comment]
Thanks for the work! Sorry for the delay. I'll take your word on all the many field definitions. Will you please fix the conflicts, then we can merge

**Comment by mborgerson** [comment]
Thanks!

**Pull request merged**
